name: Publish Package

on:
  push:
    branches: [ master ]

jobs:
  npm-publish:
    name: Publicar Pacote
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Instalar dependências
        run: npm install

      - name: Publicar Pacote
        run: npm publish --access public


